---
title           : "My preregistration for Prod and Reprod 2022"
shorttitle      : "My preregistration"
date            : "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"

author: 
  - name        : Fred Tremblay
    affiliation : 1


affiliation:
  - id          : 1
    institution : McGill University

output: prereg::prereg_pdf
---

<!-- To keep pre-registrations to a reasonable length for readers, we recommend answers fit within a single page .pdf document, roughly 3200 characters. Read more about this here: https://aspredicted.org/messages/why_limits.php -->

## Data collection

<!-- Have any data been collected for this study already? (Note: "Yes" is not an accepted answer.) -->

**Yes**, we already collected the data. The data was collected by Fred Tremblay (author), using GPS-accelerometry and DLW data from black-legged kittiwakes (Rissa tridactyla) breeding on Middleton Island, AK, in 2021

## Hypothesis

<!-- What's the main question being asked or hypothesis being tested in this study? -->

> H1: The two sample method has no significant impact on kittiwakes' energetics and behaviour compared to the single sample method when using doubly-labelled water (DLW).

> H2: The two sample method has a significant impact on kittiwakes' energetics and behaviour compared to the single sample method when using doubly-labelled water (DLW).

## Dependent variable

<!-- Describe the key dependent variable(s) specifying how they will be measured. -->

> Daily Energy Expenditure: energy expenditure measured using DLW in kJ/g*day 
> Time-activity budget: porportion of time (%) that a bird is involved in 5 behaviours (flying, swimming, resting on land, attending colony, and glidding). The behavioural classififcation was obtaine dusing GPS-accelerometry data via a Hidden Markov Model.

## Conditions

<!-- How many and which conditions will participants be assigned to? -->

> Kkititwakes will be assigned to two different treatment group: single-sample and two-sample. Each group represent a different method for measuring energy expenditure using DLW. 


## Analyses

<!-- Specify exactly which analyses you will conduct to examine the main question/hypothesis. -->

> Paired test to test for difference between 1-sample and 2-sample's DEE

> Anova to test for difference in TAB between 1-sample and 2-sample method. If difference detect with Anova, post -hoc follow up to determine the nature and direction of the difference. 

## Outliers and exclusions

<!-- Describe exactly how outliers will be defined and handled, and your precise rule(s) for excluding observations. -->

> Example 1: We will compute the overall mean and standard deviation across all conditions, and winsorize at 2.5 SD above/below the mean. Example 2: We will exclude participants who incorrectly answer at least 2 of our 3 attention check questions. Example 3: We will exclude any participants who complete the survey in less than 30 seconds.

## Sample size

<!-- How many observations will be collected or what will determine sample size? No need to justify decision, but be precise about _exactly_ how the number will be determined. -->

> We will include data from 51 kittiwakes (Single sample = 10, two-sample = 41). For all individuals, we obtained field metabolic rate and time-activity budget. To prevent a sex bias based on sex and mass difference, this study includes only males, and we will use the corrected energy expenditure to a mass of 450g for all individuals. 

## Other

<!-- Anything else you would like to pre-register? (e.g., secondary analyses, variables collected for exploratory purposes, unusual analyses planned?) -->

> The data used for this class project has been used to answer a different question. Thus, the sample size for each treatment group is not ideal and squewed. We acknoledge the bias in our data and conclusions drawn from this class project should not be extended past the scope of this course. 

## Study type

Finally. For record keeping purposes, please tell us the type of study you are pre-registering.

-   Class project or assignment


# References

## 

```{=tex}
\vspace{-2pc}
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{-1in}
\setlength{\parskip}{8pt}
```
\noindent
